"""Numerical constants sourced from Symbolica built-ins.

FSD must not carry long decimal spellings of constants such as pi or the
Euler-Mascheroni constant in Python source.  Those spellings silently cap the
precision available to arbitrary-precision rescue paths.  Keep the exact
constants as Symbolica expressions, and only ask Symbolica for a numeric value
at the precision required by the caller.
"""

from __future__ import annotations

from decimal import Decimal
from functools import lru_cache

from symbolica import E, Expression


def _real_decimal(expr: Expression, precision_digits: int) -> Decimal:
    """Evaluate a real Symbolica constant at the requested decimal precision."""
    real, imag = expr.evaluate({}, int(precision_digits))
    if not Decimal(imag).is_zero():
        raise ValueError(f"expected a real Symbolica constant, got {expr}")
    return Decimal(real)


@lru_cache(maxsize=64)
def symbolica_pi_decimal(precision_digits: int) -> Decimal:
    """Return pi as a Decimal generated by Symbolica."""
    return _real_decimal(Expression.PI, int(precision_digits))


@lru_cache(maxsize=64)
def symbolica_euler_gamma_decimal(precision_digits: int) -> Decimal:
    """Return Euler's constant as a Decimal generated by Symbolica."""
    return _real_decimal(Expression.EULER_GAMMA, int(precision_digits))


@lru_cache(maxsize=256)
def symbolica_zeta_decimal(order: int, precision_digits: int) -> Decimal:
    """Return zeta(order) as a Decimal generated by Symbolica."""
    return _real_decimal(E(f"zeta({int(order)})"), int(precision_digits))


def symbolica_real_float(expr: Expression, precision_digits: int = 80) -> float:
    """Evaluate an exact Symbolica real constant and convert it to f64."""
    return float(_real_decimal(expr, int(precision_digits)))


PI_FLOAT = symbolica_real_float(Expression.PI)
EULER_GAMMA_FLOAT = symbolica_real_float(Expression.EULER_GAMMA)
PI_SQUARED_OVER_6_FLOAT = symbolica_real_float(Expression.PI**2 / 6)
PI_SQUARED_OVER_12_FLOAT = symbolica_real_float(Expression.PI**2 / 12)
ONELOOP_TO_FEYNMAN_FLOAT = symbolica_real_float(-1 / (16 * Expression.PI**2))
